### ISSUE TITLE
UnhandledPromiseRejectionWarning & DeprecationWarning

### ISSUE THREAD

**Issue by ccaputo** [nttgin/BGPalerter#187]
**Describe the bug**
Got:

```
(node:28577) UnhandledPromiseRejectionWarning: RIPE RIS connection failed. Trying again...
(node:28577) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28577) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Are you using the binary or the source code?**
Source - tag v1.24.0 (3b23a90), with nodejs-12.14.0.

**Your information**
Chris Caputo - AS33108/SeattleIX

**Comment by massimocandela** [comment]
Thanks for reporting, this has been fixed.

**Comment by ccaputo** [comment]
Thanks for fixing.  Should there be documentation added for 'reconnectTimeoutSeconds'?

**Comment by massimocandela** [comment]
I improved and simplified further the reconnection feature. I decided to don't expose the reconnectTimeoutSeconds parameter because changing this parameter is essentially useless (it is the first value used for the reconnection attempt, the following attempts will be after reconnectTimeoutSeconds += reconnectTimeoutSeconds / 2 with min 10 sec and max 2 min).

**Comment by ccaputo** [comment]
Nice work.  Am now running 31f5348b48b4095eb9b5e7310934fc295190b2f5.

**Comment by jkldgoefgkljefogeg** [comment]
with v1.25.0 bgpalerter-linux-x64, I got

```
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:520502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
(node:520502) UnhandledPromiseRejectionWarning: Error: Request failed with status code 520
    at createError (/snapshot/build/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/snapshot/build/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/snapshot/build/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:520502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 18)

```

then BGPalerter auto restarted afterwards

**Comment by massimocandela** [comment]
Hi,

This error is coming from some API call. What report modules are you using? 
Possibly one of the report module used is calling a webhook/api that returns 520. In any case, I need to improve the error handling as soon as we discover what module is.

Can you share your config.yml file (be careful to remove possible hooks and passwords) ?

Do you get this error during auto-configuration or while it is already monitoring?

Thanks

**Comment by massimocandela** [comment]
I think I found where the exception is not handled properly. Is in the RPKI validator. I'm fixing this, it will go out with the next release. As soon as I have a binary I will let you know.

thanks for reporting

**Comment by jkldgoefgkljefogeg** [comment]
I am using default config.yml so only `reportFile` is enabled.

**Comment by massimocandela** [comment]
This is fixed, the exception is now handled. It will go out with the next release.
I also reported to the RIPE team that the VRP API it returned 520 errors. It was probably a temporary issue.
Anyway, it should not have affected the RPKI monitoring too much, what happened essentially was that the VRP list (a list of valid <prefix, origin> pairs) was older due to failures in refreshing it (possibly some hours older, not a big deal in my opinion).
