### ISSUE TITLE
prefixes.yml

### ISSUE THREAD

**Issue by mahtin** [nttgin/BGPalerter#27]
If prefixes is read only or created and owned by a different owner; then this error is thrown:
```
Error: EACCES: permission denied, open 'prefixes.yml'
```
This is because the file can be written back under some conditions. See https://github.com/nttgin/BGPalerter/blob/master/inputs/inputYml.js#L58

```
$ ls -l prefixes.yml 
-r--r--r--  1 martin  staff  289 Oct 17 02:58 prefixes.yml
$
```

```
$ ./bgpalerter-macos-x64 
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: EACCES: permission denied, open 'prefixes.yml'
    at Object.openSync (fs.js:438:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:490:32)
    at Object.writeFileSync (fs.js:1189:35)
    at _loop (/snapshot/build/inputs/inputYml.js:161:26)
    at new InputYml (/snapshot/build/inputs/inputYml.js:193:9)
    at Object.<anonymous> (/snapshot/build/env.js:200:13)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
$ 
```

**Comment by massimocandela** [comment]
Thanks for reporting this. It is indeed an error, especially because that condition can be reached also if the file is malformed (and not only when missing).

**Comment by massimocandela** [comment]
This has been fixed in release: https://github.com/nttgin/BGPalerter/releases/tag/v1.20.2
