### ISSUE TITLE
paths broken on upgrade to v1.26.1 from pre v1.26

### ISSUE THREAD

**Issue by ccaputo** [nttgin/BGPalerter#308]
**Describe the bug**

The new `volume` feature has apparently broken upgrades:

```
$ npm run watch-and-serve

> bgpalerter@1.26.1 watch-and-serve /home/foo/BGPalerter
> nodemon -e yml,js,json,txt --inspect --exec babel-node index.js

[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: yml,js,json,txt
[nodemon] starting `babel-node --inspect index.js`
Debugger listening on ws://127.0.0.1:9229/2ba4520a-8d96-40c2-bdd9-e2b0366ca598
For help, see: https://nodejs.org/en/docs/inspector
internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, mkdir './/home/foo/BGPalerter.logs'
    at Object.mkdirSync (fs.js:840:3)
    at new FileLogger (/home/foo/BGPalerter/src/utils/fileLogger.js:28:16)
    at Object.<anonymous> (/home/foo/BGPalerter/src/env.js:185:24)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._compile (/home/foo/BGPalerter/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Object.newLoader [as .js] (/home/foo/BGPalerter/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: './/home/foo/BGPalerter.logs'
}
[nodemon] app crashed - waiting for file changes before starting...
```

Config:

```
logging:
  directory: /home/foo/BGPalerter.logs
```

**Expected behavior**

Upgrade shouldn't break existing config.

**Are you using the binary or the source code?**

Source.

**Comment by massimocandela** [comment]
Hi @ccaputo,

I see what you mean. 
Thanks for reporting it.
I'm working on it.

**Comment by massimocandela** [comment]
I just pushed a patch.
I tested it and it works. Please, do a git pull and test if it works also with your configuration.
Thanks!

**Comment by ccaputo** [comment]
Fix tested here and confirmed good.  Thanks!

**Comment by massimocandela** [comment]
Thanks @ccaputo for reporting and sorry for the inconvenience.
I just release v1.26.2 containing such fix.
