### ISSUE TITLE
ReportSlack fails

### ISSUE THREAD

**Issue by lephoton** [nttgin/BGPalerter#4]
When I configure ReportSlack the program fails when loading.  Apologies, github code formatting is broken with what I've included so I've separated sections with "snip".

-- snip --
./bgpalerter-linux-x64
loading config: /home/user/tools/bgpalerter/config.yml
pkg/prelude/bootstrap.js:1185
      throw error;
      ^

Error: Cannot find module './reports/ReportSlack'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:635:17)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /snapshot/build/env.js:102:14
    at Array.map (<anonymous>)
    at Object.<anonymous> (/snapshot/build/env.js:100:41)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)

-- snip -- 

The config is as follows:

-- snip --

  - file: ReportSlack
    channels:
      - hijack
      - newprefix
      - visibility
    params:
     hookUrl: https://hooks.slack.com/services/something/something/something`

-- snip -- 

When removed it loads fine.

Running Ubuntu 18.04

**Comment by massimocandela** [comment]
Hi, try replacing `file: ReportSlack` with `file: reportSlack` in config.yml.
I changed this in the repo so nobody else hits this error.

Thanks for reporting it.

**Comment by lephoton** [comment]
That worked, thank you!
