### ISSUE TITLE
Unable to run 

### ISSUE THREAD

**Issue by telescope40** [nttgin/BGPalerter#615]
**Describe the bug**
When starting the Linux version with npm run serve. An error in the index.js is thrown 

**Error Code**
/home/bgpalerter/index.js:34
import yargs from 'yargs';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._compile (/home/bgpalerter/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/home/bgpalerter/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at Object.<anonymous> (/home/bgpalerter/node_modules/@babel/node/lib/_babel-node.js:170:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)

**Expected behavior**
BGP Alerter should start 

**Are you using the binary or the source code?**
Source Code 

**Your information**
LouD 27257

**Comment by massimocandela** [comment]
Hi @telescope40,

Please, be sure that you did "npm install" and that you have a version of node >= 12 ([see here](https://github.com/nttgin/BGPalerter/blob/main/docs/node.md)).

**Comment by telescope40** [comment]
Hey Massimo,

I reset Git to the pull from the initial 1.28.1 and performed npm intall. I did get the service working once again. Thanks for the quick response !
