### ISSUE TITLE
TypeError: params.p.split is not a function

### ISSUE THREAD

**Issue by nusenu** [nttgin/BGPalerter#62]
I'm trying to use the new feature from #28
(version 1.21.0)
```
cat p.txt
1.1.1.0/24
``` 

```
./bgpalerter-linux-x64 generate -pf p.txt  -o prefixes.yml 
/snapshot/build/index.js:51
      prefixes = params.p.split(",");
                          ^

TypeError: params.p.split is not a function
    at Object.<anonymous> (/snapshot/build/index.js:51:27)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:710:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:659:3)

```

**Comment by massimocandela** [comment]
Sorry, my bad. Try --pf instead of -pf. This is indeed an inconsistency I will fix in the next release, thanks for reporting.

**Comment by massimocandela** [comment]
Released in https://github.com/nttgin/BGPalerter/releases/tag/v1.22.0
