### ISSUE TITLE
AF_ROUTE required for 1.29.0 with "- file: reportEmail"?

### ISSUE THREAD

**Issue by prathlev** [nttgin/BGPalerter#778]
After upgrading from 1.28.4 to 1.29.0, the systemd service we use for bgpalerter fails with an "Unknown system error 97".

I use a strict systemd unit file for this service, a.o. limiting allowed address families to ``AF_INET`` and ``AF_INET6``. After upgrading to 1.29.0, I need to add ``AF_ROUTE`` for the service to start. I have ``- file: reportEmail`` enabled and if I comment out that section, the problem disappears.

The systemd unit file I use, without allowing ``AF_ROUTE``:

```
[Unit]
Description=BGPalerter
After=network.target
StartLimitBurst=3
StartLimitIntervalSec=3

[Service]
Type=simple
Restart=on-failure
User=bgpalerter
Group=bgpalerter
LockPersonality=yes
NoNewPrivileges=yes
PrivateDevices=yes
PrivateTmp=yes
ProtectControlGroups=yes
ProtectKernelModules=yes
ProtectKernelTunables=yes
ProtectHome=read-only
ReadWritePaths=/home/bgpalerter/logs
ProtectSystem=strict
ReadWritePaths=/home/bgpalerter
RestrictNamespaces=yes
RestrictRealtime=yes
SystemCallArchitectures=native
SystemCallErrorNumber=EPERM
SystemCallFilter=@system-service
SystemCallFilter=~@debug @privileged @resources
WorkingDirectory=/home/bgpalerter
ExecStart=/usr/local/bin/bgpalerter-linux-x64 -d /home/bgpalerter/
# Make sure the process runs with no capabilities
CapabilityBoundingSet=
UMask=0077
RemoveIPC=yes
PrivateUsers=yes
RestrictSUIDSGID=yes
# *** The following settings lower the security *** 
# *** but are necessary for the service to work *** 
# The Node.js precompiled binary seems to build and run code on-the-fly 
MemoryDenyWriteExecute=no
# The service needs to connect to the RIPE RIS service 
RestrictAddressFamilies=AF_INET AF_INET6

[Install]
WantedBy=multi-user.target
```

The messages logged when starting the service are:

```
Mar  2 16:04:32 test-prat-vm-2 systemd[1]: Started BGPalerter.
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]: Loaded config: /home/bgpalerter/config.yml
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]: pkg/prelude/bootstrap.js:1740
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:      throw error;
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:      ^
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 97 (Unknown system error 97)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Object.networkInterfaces (os.js:259:16)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Object.<anonymous> (/snapshot/BGPalerter/node_modules/nodemailer/lib/shared/index.js:15:66)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Module._compile (pkg/prelude/bootstrap.js:1794:22)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Module.load (internal/modules/cjs/loader.js:950:32)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Module.require (internal/modules/cjs/loader.js:974:19)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Module.require (pkg/prelude/bootstrap.js:1719:31)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at require (internal/modules/cjs/helpers.js:93:18)
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    at Object.<anonymous> (/snapshot/BGPalerter/node_modules/nodemailer/lib/mailer/index.js:4:16) {
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:  code: 'ERR_SYSTEM_ERROR',
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:  info: {
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    errno: 97,
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    code: 'Unknown system error 97',
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    message: 'Unknown system error 97',
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:    syscall: 'uv_interface_addresses'
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:  },
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:  errno: [Getter/Setter],
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]:  syscall: [Getter/Setter]
Mar  2 16:04:33 test-prat-vm-2 bgpalerter-linux-x64[71805]: }
Mar  2 16:04:33 test-prat-vm-2 systemd[1]: bgpalerter.service: Main process exited, code=exited, status=1/FAILURE
Mar  2 16:04:33 test-prat-vm-2 systemd[1]: bgpalerter.service: Failed with result 'exit-code'.
```

With a freshly generated config.yml, with only the following lines uncommented/enabled, the service is unable to start:

```
  - file: reportEmail
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
      - roa
```

If I then allow ``AF_ROUTE`` in the systemd unit file, the service starts as it should.

I am using the binary downloaded from [https://github.com/nttgin/BGPalerter/releases/download/v1.29.0/bgpalerter-linux-x64](https://github.com/nttgin/BGPalerter/releases/download/v1.29.0/bgpalerter-linux-x64).

Adding ``AF_ROUTE`` is the easy work around of course, but I am uncertain why this process would need that. I suspect that it is an underlying thing in NPM 14 or something like that, but my google-fu is not strong enough to find out.

With the systemd service limited in multiple other ways, I guess allowing ``AF_ROUTE`` shouldn't present a security issue.

Since this is probably not a bug in bgpalerter, feel free to close the issue without further ado.

And thank you for a nice piece of software! We (TDC NET, AS3292) have it running in test currently and hope to have it operational soon. Feel free to update the "[Who is using BGPalerter](https://github.com/nttgin/BGPalerter/blob/main/docs/friends.md)" page and let me know if you need info from a work related email. (I didn't think that completely through when I created the account. :-))

-- 
Peter Rathlev, TDC NET / AS3292

**Comment by massimocandela** [comment]
Hi @prathlev, 

Thanks for reporting.
I see that it is coming from nodemailer, but I suspect it is more related to the upgrade to node 14 (summary: I have no idea why). As you said, I don't believe I can do anything about it.

I will happily add TDC NET (AS3292) in freinds.md :)
